DELETE FROM culinaryvalues;
DELETE FROM healthvalues;
DELETE FROM categories;
DELETE FROM tastes;
DELETE FROM colors;
DELETE FROM visits;
DELETE FROM users;
DELETE FROM reports;
DELETE FROM report_tastes;
DELETE FROM comments;

INSERT INTO culinaryvalues (name, description) VALUES ('Delicacy', 'Potentially valuable for trade');
INSERT INTO culinaryvalues (name, description) VALUES ('Palatable', 'An acquired taste, perhaps');
INSERT INTO culinaryvalues (name, description) VALUES ('Inpalatable', 'Unilaterally foul, does not belong in a kitchen');

INSERT INTO healthvalues (name, description) VALUES ('Edible', 'Can be part of a healthy diet');
INSERT INTO healthvalues (name, description) VALUES ('Indigestible', 'Stomach aches, but no long term effects');
INSERT INTO healthvalues (name, description) VALUES ('Poisonous', 'Causes bodily harm but is not immediately fatal');
INSERT INTO healthvalues (name, description) VALUES ('Deadly', 'Potentially fatal in meal sized doses');
INSERT INTO healthvalues (name, description) VALUES ('Unknown', 'No effects to health reported yet');

INSERT INTO categories (name) VALUES ('Russula');
INSERT INTO categories (name) VALUES ('Milk cap');
INSERT INTO categories (name) VALUES ('Bolete');
INSERT INTO categories (name) VALUES ('Chanterelle');
INSERT INTO categories (name) VALUES ('Polypore');
INSERT INTO categories (name) VALUES ('Cortinar');
INSERT INTO categories (name) VALUES ('Tricholoma');
INSERT INTO categories (name) VALUES ('Waxcap');
INSERT INTO categories (name) VALUES ('Clitocybe');
INSERT INTO categories (name) VALUES ('Tooth fungi');
INSERT INTO categories (name) VALUES ('Puffball');
INSERT INTO categories (name) VALUES ('Bonnet mushroom');
INSERT INTO categories (name) VALUES ('Morel');
INSERT INTO categories (name) VALUES ('Slime mold');
INSERT INTO categories (name) VALUES ('Ink cap');

INSERT INTO tastes (name, description) VALUES ('Mild', 'gentle, not strong or distinctive');
INSERT INTO tastes (name, description) VALUES ('Sweet', 'sugary or pleasant');
INSERT INTO tastes (name, description) VALUES ('Nutty', 'similar to nuts');
INSERT INTO tastes (name, description) VALUES ('Earthy', 'reminiscent of soil or forest floor');
INSERT INTO tastes (name, description) VALUES ('Peppery', 'sharp, spicy, like black pepper');
INSERT INTO tastes (name, description) VALUES ('Bitter', 'unpleasantly sharp or acrid');
INSERT INTO tastes (name, description) VALUES ('Acrid', 'harsh, burning, or irritating');
INSERT INTO tastes (name, description) VALUES ('Mealy', 'like raw flour or grain');
INSERT INTO tastes (name, description) VALUES ('Fishy', 'reminiscent of fish');
INSERT INTO tastes (name, description) VALUES ('Metallic', 'like metal');
INSERT INTO tastes (name, description) VALUES ('Soapy', 'like soap');
INSERT INTO tastes (name, description) VALUES ('Burning', 'causes a burning sensation');
INSERT INTO tastes (name, description) VALUES ('Hot', 'spicy or pungent');
INSERT INTO tastes (name, description) VALUES ('Pungent', 'strong and sharp');
INSERT INTO tastes (name, description) VALUES ('Chemical', 'artificial or synthetic taste');
INSERT INTO tastes (name, description) VALUES ('Rancid', 'spoiled or rotten fat taste');
INSERT INTO tastes (name, description) VALUES ('Garlicky', 'reminiscent of garlic');
INSERT INTO tastes (name, description) VALUES ('Radish-like', 'similar to raw radish');
INSERT INTO tastes (name, description) VALUES ('Unpleasant', 'generally bad or off-putting');

INSERT INTO colors (name, hex) VALUES ('Black', '#000000');
INSERT INTO colors (name, hex) VALUES ('Night', '#0C090A');
INSERT INTO colors (name, hex) VALUES ('Gunmetal', '#2C3539');
INSERT INTO colors (name, hex) VALUES ('Midnight', '#2B1B17');
INSERT INTO colors (name, hex) VALUES ('Charcoal', '#34282C');
INSERT INTO colors (name, hex) VALUES ('Dark Slate Grey', '#25383C');
INSERT INTO colors (name, hex) VALUES ('Oil', '#3B3131');
INSERT INTO colors (name, hex) VALUES ('Black Cat', '#413839');
INSERT INTO colors (name, hex) VALUES ('Iridium', '#3D3C3A');
INSERT INTO colors (name, hex) VALUES ('Black Eel', '#463E3F');
INSERT INTO colors (name, hex) VALUES ('Black Cow', '#4C4646');
INSERT INTO colors (name, hex) VALUES ('Gray Wolf', '#504A4B');
INSERT INTO colors (name, hex) VALUES ('Vampire Gray', '#565051');
INSERT INTO colors (name, hex) VALUES ('Gray Dolphin', '#5C5858');
INSERT INTO colors (name, hex) VALUES ('Carbon Gray', '#625D5D');
INSERT INTO colors (name, hex) VALUES ('Ash Gray', '#666362');
INSERT INTO colors (name, hex) VALUES ('Cloudy Gray', '#6D6968');
INSERT INTO colors (name, hex) VALUES ('Smokey Gray', '#726E6D');
INSERT INTO colors (name, hex) VALUES ('Gray', '#736F6E');
INSERT INTO colors (name, hex) VALUES ('Granite', '#837E7C');
INSERT INTO colors (name, hex) VALUES ('Battleship Gray', '#848482');
INSERT INTO colors (name, hex) VALUES ('Gray Cloud', '#B6B6B4');
INSERT INTO colors (name, hex) VALUES ('Gray Goose', '#D1D0CE');
INSERT INTO colors (name, hex) VALUES ('Platinum', '#E5E4E2');
INSERT INTO colors (name, hex) VALUES ('Metallic Silver', '#BCC6CC');
INSERT INTO colors (name, hex) VALUES ('Blue Gray', '#98AFC7');
INSERT INTO colors (name, hex) VALUES ('Light Slate Gray', '#6D7B8D');
INSERT INTO colors (name, hex) VALUES ('Slate Gray', '#657383');
INSERT INTO colors (name, hex) VALUES ('Jet Gray', '#616D7E');
INSERT INTO colors (name, hex) VALUES ('Mist Blue', '#646D7E');
INSERT INTO colors (name, hex) VALUES ('Marble Blue', '#566D7E');
INSERT INTO colors (name, hex) VALUES ('Slate Blue', '#737CA1');
INSERT INTO colors (name, hex) VALUES ('Steel Blue', '#4863A0');
INSERT INTO colors (name, hex) VALUES ('Blue Jay', '#2B547E');
INSERT INTO colors (name, hex) VALUES ('Dark Slate Blue', '#2B3856');
INSERT INTO colors (name, hex) VALUES ('Midnight Blue', '#151B54');
INSERT INTO colors (name, hex) VALUES ('Navy Blue', '#000080');
INSERT INTO colors (name, hex) VALUES ('Blue Whale', '#342D7E');
INSERT INTO colors (name, hex) VALUES ('Lapis Blue', '#15317E');
INSERT INTO colors (name, hex) VALUES ('Denim Dark Blue', '#151B8D');
INSERT INTO colors (name, hex) VALUES ('Earth Blue', '#0000A0');
INSERT INTO colors (name, hex) VALUES ('Cobalt Blue', '#0020C2');
INSERT INTO colors (name, hex) VALUES ('Blueberry Blue', '#0041C2');
INSERT INTO colors (name, hex) VALUES ('Sapphire Blue', '#2554C7');
INSERT INTO colors (name, hex) VALUES ('Blue Eyes', '#1569C7');
INSERT INTO colors (name, hex) VALUES ('Royal Blue', '#2B60DE');
INSERT INTO colors (name, hex) VALUES ('Blue Orchid', '#1F45FC');
INSERT INTO colors (name, hex) VALUES ('Blue Lotus', '#6960EC');
INSERT INTO colors (name, hex) VALUES ('Light Slate Blue', '#736AFF');
INSERT INTO colors (name, hex) VALUES ('Windows Blue', '#357EC7');
INSERT INTO colors (name, hex) VALUES ('Glacial Blue Ice', '#368BC1');
INSERT INTO colors (name, hex) VALUES ('Silk Blue', '#488AC7');
INSERT INTO colors (name, hex) VALUES ('Blue Ivy', '#3090C7');
INSERT INTO colors (name, hex) VALUES ('Blue Koi', '#659EC7');
INSERT INTO colors (name, hex) VALUES ('Columbia Blue', '#87AFC7');
INSERT INTO colors (name, hex) VALUES ('Baby Blue', '#95B9C7');
INSERT INTO colors (name, hex) VALUES ('Light Steel Blue', '#728FCE');
INSERT INTO colors (name, hex) VALUES ('Ocean Blue', '#2B65EC');
INSERT INTO colors (name, hex) VALUES ('Blue Ribbon', '#306EFF');
INSERT INTO colors (name, hex) VALUES ('Blue Dress', '#157DEC');
INSERT INTO colors (name, hex) VALUES ('Dodger Blue', '#1589FF');
INSERT INTO colors (name, hex) VALUES ('Cornflower Blue', '#6495ED');
INSERT INTO colors (name, hex) VALUES ('Sky Blue', '#6698FF');
INSERT INTO colors (name, hex) VALUES ('Butterfly Blue', '#38ACEC');
INSERT INTO colors (name, hex) VALUES ('Iceberg', '#56A5EC');
INSERT INTO colors (name, hex) VALUES ('Crystal Blue', '#5CB3FF');
INSERT INTO colors (name, hex) VALUES ('Deep Sky Blue', '#3BB9FF');
INSERT INTO colors (name, hex) VALUES ('Denim Blue', '#79BAEC');
INSERT INTO colors (name, hex) VALUES ('Light Sky Blue', '#82CAFA');
INSERT INTO colors (name, hex) VALUES ('Day Sky Blue', '#82CAFF');
INSERT INTO colors (name, hex) VALUES ('Jeans Blue', '#A0CFEC');
INSERT INTO colors (name, hex) VALUES ('Blue Angel', '#B7CEEC');
INSERT INTO colors (name, hex) VALUES ('Pastel Blue', '#B4CFEC');
INSERT INTO colors (name, hex) VALUES ('Sea Blue', '#C2DFFF');
INSERT INTO colors (name, hex) VALUES ('Powder Blue', '#C6DEFF');
INSERT INTO colors (name, hex) VALUES ('Coral Blue', '#AFDCEC');
INSERT INTO colors (name, hex) VALUES ('Light Blue', '#ADDFFF');
INSERT INTO colors (name, hex) VALUES ('Robin Egg Blue', '#BDEDFF');
INSERT INTO colors (name, hex) VALUES ('Pale Blue Lily', '#CFECEC');
INSERT INTO colors (name, hex) VALUES ('Light Cyan', '#E0FFFF');
INSERT INTO colors (name, hex) VALUES ('Water', '#EBF4FA');
INSERT INTO colors (name, hex) VALUES ('AliceBlue', '#F0F8FF');
INSERT INTO colors (name, hex) VALUES ('Azure', '#F0FFFF');
INSERT INTO colors (name, hex) VALUES ('Light Slate', '#CCFFFF');
INSERT INTO colors (name, hex) VALUES ('Light Aquamarine', '#93FFE8');
INSERT INTO colors (name, hex) VALUES ('Electric Blue', '#9AFEFF');
INSERT INTO colors (name, hex) VALUES ('Aquamarine', '#7FFFD4');
INSERT INTO colors (name, hex) VALUES ('Cyan or Aqua', '#00FFFF');
INSERT INTO colors (name, hex) VALUES ('Tron Blue', '#7DFDFE');
INSERT INTO colors (name, hex) VALUES ('Blue Zircon', '#57FEFF');
INSERT INTO colors (name, hex) VALUES ('Blue Lagoon', '#8EEBEC');
INSERT INTO colors (name, hex) VALUES ('Celeste', '#50EBEC');
INSERT INTO colors (name, hex) VALUES ('Blue Diamond', '#4EE2EC');
INSERT INTO colors (name, hex) VALUES ('Tiffany Blue', '#81D8D0');
INSERT INTO colors (name, hex) VALUES ('Cyan Opaque', '#92C7C7');
INSERT INTO colors (name, hex) VALUES ('Blue Hosta', '#77BFC7');
INSERT INTO colors (name, hex) VALUES ('Northern Lights Blue', '#78C7C7');
INSERT INTO colors (name, hex) VALUES ('Medium Turquoise', '#48CCCD');
INSERT INTO colors (name, hex) VALUES ('Turquoise', '#43C6DB');
INSERT INTO colors (name, hex) VALUES ('Jellyfish', '#46C7C7');
INSERT INTO colors (name, hex) VALUES ('Blue green', '#7BCCB5');
INSERT INTO colors (name, hex) VALUES ('Macaw Blue Green', '#43BFC7');
INSERT INTO colors (name, hex) VALUES ('Light Sea Green', '#3EA99F');
INSERT INTO colors (name, hex) VALUES ('Dark Turquoise', '#3B9C9C');
INSERT INTO colors (name, hex) VALUES ('Sea Turtle Green', '#438D80');
INSERT INTO colors (name, hex) VALUES ('Medium Aquamarine', '#348781');
INSERT INTO colors (name, hex) VALUES ('Greenish Blue', '#307D7E');
INSERT INTO colors (name, hex) VALUES ('Grayish Turquoise', '#5E7D7E');
INSERT INTO colors (name, hex) VALUES ('Beetle Green', '#4C787E');
INSERT INTO colors (name, hex) VALUES ('Teal', '#008080');
INSERT INTO colors (name, hex) VALUES ('Sea Green', '#4E8975');
INSERT INTO colors (name, hex) VALUES ('Camouflage Green', '#78866B');
INSERT INTO colors (name, hex) VALUES ('Sage Green', '#848b79');
INSERT INTO colors (name, hex) VALUES ('Hazel Green', '#617C58');
INSERT INTO colors (name, hex) VALUES ('Venom Green', '#728C00');
INSERT INTO colors (name, hex) VALUES ('Fern Green', '#667C26');
INSERT INTO colors (name, hex) VALUES ('Dark Forest Green', '#254117');
INSERT INTO colors (name, hex) VALUES ('Medium Sea Green', '#306754');
INSERT INTO colors (name, hex) VALUES ('Medium Forest Green', '#347235');
INSERT INTO colors (name, hex) VALUES ('Seaweed Green', '#437C17');
INSERT INTO colors (name, hex) VALUES ('Pine Green', '#387C44');
INSERT INTO colors (name, hex) VALUES ('Jungle Green', '#347C2C');
INSERT INTO colors (name, hex) VALUES ('Shamrock Green', '#347C17');
INSERT INTO colors (name, hex) VALUES ('Medium Spring Green', '#348017');
INSERT INTO colors (name, hex) VALUES ('Forest Green', '#4E9258');
INSERT INTO colors (name, hex) VALUES ('Green Onion', '#6AA121');
INSERT INTO colors (name, hex) VALUES ('Spring Green', '#4AA02C');
INSERT INTO colors (name, hex) VALUES ('Lime Green', '#41A317');
INSERT INTO colors (name, hex) VALUES ('Clover Green', '#3EA055');
INSERT INTO colors (name, hex) VALUES ('Green Snake', '#6CBB3C');
INSERT INTO colors (name, hex) VALUES ('Alien Green', '#6CC417');
INSERT INTO colors (name, hex) VALUES ('Green Apple', '#4CC417');
INSERT INTO colors (name, hex) VALUES ('Yellow Green', '#52D017');
INSERT INTO colors (name, hex) VALUES ('Kelly Green', '#4CC552');
INSERT INTO colors (name, hex) VALUES ('Zombie Green', '#54C571');
INSERT INTO colors (name, hex) VALUES ('Frog Green', '#99C68E');
INSERT INTO colors (name, hex) VALUES ('Green Peas', '#89C35C');
INSERT INTO colors (name, hex) VALUES ('Dollar Bill Green', '#85BB65');
INSERT INTO colors (name, hex) VALUES ('Dark Sea Green', '#8BB381');
INSERT INTO colors (name, hex) VALUES ('Iguana Green', '#9CB071');
INSERT INTO colors (name, hex) VALUES ('Avocado Green', '#B2C248');
INSERT INTO colors (name, hex) VALUES ('Pistachio Green', '#9DC209');
INSERT INTO colors (name, hex) VALUES ('Salad Green', '#A1C935');
INSERT INTO colors (name, hex) VALUES ('Hummingbird Green', '#7FE817');
INSERT INTO colors (name, hex) VALUES ('Nebula Green', '#59E817');
INSERT INTO colors (name, hex) VALUES ('Stoplight Go Green', '#57E964');
INSERT INTO colors (name, hex) VALUES ('Algae Green', '#64E986');
INSERT INTO colors (name, hex) VALUES ('Jade Green', '#5EFB6E');
INSERT INTO colors (name, hex) VALUES ('Green', '#00FF00');
INSERT INTO colors (name, hex) VALUES ('Emerald Green', '#5FFB17');
INSERT INTO colors (name, hex) VALUES ('Lawn Green', '#87F717');
INSERT INTO colors (name, hex) VALUES ('Chartreuse', '#8AFB17');
INSERT INTO colors (name, hex) VALUES ('Dragon Green', '#6AFB92');
INSERT INTO colors (name, hex) VALUES ('Mint green', '#98FF98');
INSERT INTO colors (name, hex) VALUES ('Green Thumb', '#B5EAAA');
INSERT INTO colors (name, hex) VALUES ('Light Jade', '#C3FDB8');
INSERT INTO colors (name, hex) VALUES ('Tea Green', '#CCFB5D');
INSERT INTO colors (name, hex) VALUES ('Green Yellow', '#B1FB17');
INSERT INTO colors (name, hex) VALUES ('Slime Green', '#BCE954');
INSERT INTO colors (name, hex) VALUES ('Goldenrod', '#EDDA74');
INSERT INTO colors (name, hex) VALUES ('Harvest Gold', '#EDE275');
INSERT INTO colors (name, hex) VALUES ('Sun Yellow', '#FFE87C');
INSERT INTO colors (name, hex) VALUES ('Yellow', '#FFFF00');
INSERT INTO colors (name, hex) VALUES ('Corn Yellow', '#FFF380');
INSERT INTO colors (name, hex) VALUES ('Parchment', '#FFFFC2');
INSERT INTO colors (name, hex) VALUES ('Cream', '#FFFFCC');
INSERT INTO colors (name, hex) VALUES ('Lemon Chiffon', '#FFF8C6');
INSERT INTO colors (name, hex) VALUES ('Cornsilk', '#FFF8DC');
INSERT INTO colors (name, hex) VALUES ('Beige', '#F5F5DC');
INSERT INTO colors (name, hex) VALUES ('Blonde', '#FBF6D9');
INSERT INTO colors (name, hex) VALUES ('AntiqueWhite', '#FAEBD7');
INSERT INTO colors (name, hex) VALUES ('Champagne', '#F7E7CE');
INSERT INTO colors (name, hex) VALUES ('BlanchedAlmond', '#FFEBCD');
INSERT INTO colors (name, hex) VALUES ('Vanilla', '#F3E5AB');
INSERT INTO colors (name, hex) VALUES ('Tan Brown', '#ECE5B6');
INSERT INTO colors (name, hex) VALUES ('Peach', '#FFE5B4');
INSERT INTO colors (name, hex) VALUES ('Mustard', '#FFDB58');
INSERT INTO colors (name, hex) VALUES ('Rubber Ducky Yellow', '#FFD801');
INSERT INTO colors (name, hex) VALUES ('Bright Gold', '#FDD017');
INSERT INTO colors (name, hex) VALUES ('Golden brown', '#EAC117');
INSERT INTO colors (name, hex) VALUES ('Macaroni and Cheese', '#F2BB66');
INSERT INTO colors (name, hex) VALUES ('Saffron', '#FBB917');
INSERT INTO colors (name, hex) VALUES ('Beer', '#FBB117');
INSERT INTO colors (name, hex) VALUES ('Cantaloupe', '#FFA62F');
INSERT INTO colors (name, hex) VALUES ('Bee Yellow', '#E9AB17');
INSERT INTO colors (name, hex) VALUES ('Brown Sugar', '#E2A76F');
INSERT INTO colors (name, hex) VALUES ('BurlyWood', '#DEB887');
INSERT INTO colors (name, hex) VALUES ('Deep Peach', '#FFCBA4');
INSERT INTO colors (name, hex) VALUES ('Ginger Brown', '#C9BE62');
INSERT INTO colors (name, hex) VALUES ('School Bus Yellow', '#E8A317');
INSERT INTO colors (name, hex) VALUES ('Sandy Brown', '#EE9A4D');
INSERT INTO colors (name, hex) VALUES ('Fall Leaf Brown', '#C8B560');
INSERT INTO colors (name, hex) VALUES ('Orange Gold', '#D4A017');
INSERT INTO colors (name, hex) VALUES ('Sand', '#C2B280');
INSERT INTO colors (name, hex) VALUES ('Cookie Brown', '#C7A317');
INSERT INTO colors (name, hex) VALUES ('Caramel', '#C68E17');
INSERT INTO colors (name, hex) VALUES ('Brass', '#B5A642');
INSERT INTO colors (name, hex) VALUES ('Khaki', '#ADA96E');
INSERT INTO colors (name, hex) VALUES ('Camel brown', '#C19A6B');
INSERT INTO colors (name, hex) VALUES ('Bronze', '#CD7F32');
INSERT INTO colors (name, hex) VALUES ('Tiger Orange', '#C88141');
INSERT INTO colors (name, hex) VALUES ('Cinnamon', '#C58917');
INSERT INTO colors (name, hex) VALUES ('Bullet Shell', '#AF9B60');
INSERT INTO colors (name, hex) VALUES ('Dark Goldenrod', '#AF7817');
INSERT INTO colors (name, hex) VALUES ('Copper', '#B87333');
INSERT INTO colors (name, hex) VALUES ('Wood', '#966F33');
INSERT INTO colors (name, hex) VALUES ('Oak Brown', '#806517');
INSERT INTO colors (name, hex) VALUES ('Moccasin', '#827839');
INSERT INTO colors (name, hex) VALUES ('Army Brown', '#827B60');
INSERT INTO colors (name, hex) VALUES ('Sandstone', '#786D5F');
INSERT INTO colors (name, hex) VALUES ('Mocha', '#493D26');
INSERT INTO colors (name, hex) VALUES ('Taupe', '#483C32');
INSERT INTO colors (name, hex) VALUES ('Coffee', '#6F4E37');
INSERT INTO colors (name, hex) VALUES ('Brown Bear', '#835C3B');
INSERT INTO colors (name, hex) VALUES ('Red Dirt', '#7F5217');
INSERT INTO colors (name, hex) VALUES ('Sepia', '#7F462C');
INSERT INTO colors (name, hex) VALUES ('Orange Salmon', '#C47451');
INSERT INTO colors (name, hex) VALUES ('Rust', '#C36241');
INSERT INTO colors (name, hex) VALUES ('Red Fox', '#C35817');
INSERT INTO colors (name, hex) VALUES ('Chocolate', '#C85A17');
INSERT INTO colors (name, hex) VALUES ('Sedona', '#CC6600');
INSERT INTO colors (name, hex) VALUES ('Papaya Orange', '#E56717');
INSERT INTO colors (name, hex) VALUES ('Halloween Orange', '#E66C2C');
INSERT INTO colors (name, hex) VALUES ('Pumpkin Orange', '#F87217');
INSERT INTO colors (name, hex) VALUES ('Construction Cone Orange', '#F87431');
INSERT INTO colors (name, hex) VALUES ('Sunrise Orange', '#E67451');
INSERT INTO colors (name, hex) VALUES ('Mango Orange', '#FF8040');
INSERT INTO colors (name, hex) VALUES ('Dark Orange', '#F88017');
INSERT INTO colors (name, hex) VALUES ('Coral', '#FF7F50');
INSERT INTO colors (name, hex) VALUES ('Basket Ball Orange', '#F88158');
INSERT INTO colors (name, hex) VALUES ('Light Salmon', '#F9966B');
INSERT INTO colors (name, hex) VALUES ('Tangerine', '#E78A61');
INSERT INTO colors (name, hex) VALUES ('Dark Salmon', '#E18B6B');
INSERT INTO colors (name, hex) VALUES ('Light Coral', '#E77471');
INSERT INTO colors (name, hex) VALUES ('Bean Red', '#F75D59');
INSERT INTO colors (name, hex) VALUES ('Valentine Red', '#E55451');
INSERT INTO colors (name, hex) VALUES ('Shocking Orange', '#E55B3C');
INSERT INTO colors (name, hex) VALUES ('Red', '#FF0000');
INSERT INTO colors (name, hex) VALUES ('Scarlet', '#FF2400');
INSERT INTO colors (name, hex) VALUES ('Ruby Red', '#F62217');
INSERT INTO colors (name, hex) VALUES ('Ferrari Red', '#F70D1A');
INSERT INTO colors (name, hex) VALUES ('Fire Engine Red', '#F62817');
INSERT INTO colors (name, hex) VALUES ('Lava Red', '#E42217');
INSERT INTO colors (name, hex) VALUES ('Love Red', '#E41B17');
INSERT INTO colors (name, hex) VALUES ('Grapefruit', '#DC381F');
INSERT INTO colors (name, hex) VALUES ('Chestnut Red', '#C34A2C');
INSERT INTO colors (name, hex) VALUES ('Cherry Red', '#C24641');
INSERT INTO colors (name, hex) VALUES ('Mahogany', '#C04000');
INSERT INTO colors (name, hex) VALUES ('Chilli Pepper', '#C11B17');
INSERT INTO colors (name, hex) VALUES ('Cranberry', '#9F000F');
INSERT INTO colors (name, hex) VALUES ('Red Wine', '#990012');
INSERT INTO colors (name, hex) VALUES ('Burgundy', '#8C001A');
INSERT INTO colors (name, hex) VALUES ('Chestnut', '#954535');
INSERT INTO colors (name, hex) VALUES ('Blood Red', '#7E3517');
INSERT INTO colors (name, hex) VALUES ('Sienna', '#8A4117');
INSERT INTO colors (name, hex) VALUES ('Sangria', '#7E3817');
INSERT INTO colors (name, hex) VALUES ('Firebrick', '#800517');
INSERT INTO colors (name, hex) VALUES ('Maroon', '#810541');
INSERT INTO colors (name, hex) VALUES ('Plum Pie', '#7D0541');
INSERT INTO colors (name, hex) VALUES ('Velvet Maroon', '#7E354D');
INSERT INTO colors (name, hex) VALUES ('Plum Velvet', '#7D0552');
INSERT INTO colors (name, hex) VALUES ('Rosy Finch', '#7F4E52');
INSERT INTO colors (name, hex) VALUES ('Puce', '#7F5A58');
INSERT INTO colors (name, hex) VALUES ('Dull Purple', '#7F525D');
INSERT INTO colors (name, hex) VALUES ('Rosy Brown', '#B38481');
INSERT INTO colors (name, hex) VALUES ('Khaki Rose', '#C5908E');
INSERT INTO colors (name, hex) VALUES ('Pink Bow', '#C48189');
INSERT INTO colors (name, hex) VALUES ('Lipstick Pink', '#C48793');
INSERT INTO colors (name, hex) VALUES ('Rose', '#E8ADAA');
INSERT INTO colors (name, hex) VALUES ('Rose Gold', '#ECC5C0');
INSERT INTO colors (name, hex) VALUES ('Desert Sand', '#EDC9AF');
INSERT INTO colors (name, hex) VALUES ('Pig Pink', '#FDD7E4');
INSERT INTO colors (name, hex) VALUES ('Cotton Candy', '#FCDFFF');
INSERT INTO colors (name, hex) VALUES ('Pink Bubblegum', '#FFDFDD');
INSERT INTO colors (name, hex) VALUES ('Misty Rose', '#FBBBB9');
INSERT INTO colors (name, hex) VALUES ('Pink', '#FAAFBE');
INSERT INTO colors (name, hex) VALUES ('Light Pink', '#FAAFBA');
INSERT INTO colors (name, hex) VALUES ('Flamingo Pink', '#F9A7B0');
INSERT INTO colors (name, hex) VALUES ('Pink Rose', '#E7A1B0');
INSERT INTO colors (name, hex) VALUES ('Pink Daisy', '#E799A3');
INSERT INTO colors (name, hex) VALUES ('Cadillac Pink', '#E38AAE');
INSERT INTO colors (name, hex) VALUES ('Carnation Pink', '#F778A1');
INSERT INTO colors (name, hex) VALUES ('Blush Red', '#E56E94');
INSERT INTO colors (name, hex) VALUES ('Hot Pink', '#F660AB');
INSERT INTO colors (name, hex) VALUES ('Watermelon Pink', '#FC6C85');
INSERT INTO colors (name, hex) VALUES ('Violet Red', '#F6358A');
INSERT INTO colors (name, hex) VALUES ('Deep Pink', '#F52887');
INSERT INTO colors (name, hex) VALUES ('Pink Cupcake', '#E45E9D');
INSERT INTO colors (name, hex) VALUES ('Pink Lemonade', '#E4287C');
INSERT INTO colors (name, hex) VALUES ('Neon Pink', '#F535AA');
INSERT INTO colors (name, hex) VALUES ('Magenta', '#FF00FF');
INSERT INTO colors (name, hex) VALUES ('Dimorphotheca Magenta', '#E3319D');
INSERT INTO colors (name, hex) VALUES ('Bright Neon Pink', '#F433FF');
INSERT INTO colors (name, hex) VALUES ('Pale Violet Red', '#D16587');
INSERT INTO colors (name, hex) VALUES ('Tulip Pink', '#C25A7C');
INSERT INTO colors (name, hex) VALUES ('Medium Violet Red', '#CA226B');
INSERT INTO colors (name, hex) VALUES ('Rogue Pink', '#C12869');
INSERT INTO colors (name, hex) VALUES ('Burnt Pink', '#C12267');
INSERT INTO colors (name, hex) VALUES ('Bashful Pink', '#C25283');
INSERT INTO colors (name, hex) VALUES ('Dark Carnation Pink', '#C12283');
INSERT INTO colors (name, hex) VALUES ('Plum', '#B93B8F');
INSERT INTO colors (name, hex) VALUES ('Viola Purple', '#7E587E');
INSERT INTO colors (name, hex) VALUES ('Purple Iris', '#571B7E');
INSERT INTO colors (name, hex) VALUES ('Plum Purple', '#583759');
INSERT INTO colors (name, hex) VALUES ('Indigo', '#4B0082');
INSERT INTO colors (name, hex) VALUES ('Purple Monster', '#461B7E');
INSERT INTO colors (name, hex) VALUES ('Purple Haze', '#4E387E');
INSERT INTO colors (name, hex) VALUES ('Eggplant', '#614051');
INSERT INTO colors (name, hex) VALUES ('Grape', '#5E5A80');
INSERT INTO colors (name, hex) VALUES ('Purple Jam', '#6A287E');
INSERT INTO colors (name, hex) VALUES ('Dark Orchid', '#7D1B7E');
INSERT INTO colors (name, hex) VALUES ('Purple Flower', '#A74AC7');
INSERT INTO colors (name, hex) VALUES ('Medium Orchid', '#B048B5');
INSERT INTO colors (name, hex) VALUES ('Purple Amethyst', '#6C2DC7');
INSERT INTO colors (name, hex) VALUES ('Dark Violet', '#842DCE');
INSERT INTO colors (name, hex) VALUES ('Violet', '#8D38C9');
INSERT INTO colors (name, hex) VALUES ('Purple Sage Bush', '#7A5DC7');
INSERT INTO colors (name, hex) VALUES ('Lovely Purple', '#7F38EC');
INSERT INTO colors (name, hex) VALUES ('Purple', '#8E35EF');
INSERT INTO colors (name, hex) VALUES ('Aztech Purple', '#893BFF');
INSERT INTO colors (name, hex) VALUES ('Medium Purple', '#8467D7');
INSERT INTO colors (name, hex) VALUES ('Jasmine Purple', '#A23BEC');
INSERT INTO colors (name, hex) VALUES ('Purple Daffodil', '#B041FF');
INSERT INTO colors (name, hex) VALUES ('Tyrian Purple', '#C45AEC');
INSERT INTO colors (name, hex) VALUES ('Crocus Purple', '#9172EC');
INSERT INTO colors (name, hex) VALUES ('Purple Mimosa', '#9E7BFF');
INSERT INTO colors (name, hex) VALUES ('Heliotrope Purple', '#D462FF');
INSERT INTO colors (name, hex) VALUES ('Crimson', '#E238EC');
INSERT INTO colors (name, hex) VALUES ('Purple Dragon', '#C38EC7');
INSERT INTO colors (name, hex) VALUES ('Lilac', '#C8A2C8');
INSERT INTO colors (name, hex) VALUES ('Blush Pink', '#E6A9EC');
INSERT INTO colors (name, hex) VALUES ('Mauve', '#E0B0FF');
INSERT INTO colors (name, hex) VALUES ('Wisteria Purple', '#C6AEC7');
INSERT INTO colors (name, hex) VALUES ('Blossom Pink', '#F9B7FF');
INSERT INTO colors (name, hex) VALUES ('Thistle', '#D2B9D3');
INSERT INTO colors (name, hex) VALUES ('Periwinkle', '#E9CFEC');
INSERT INTO colors (name, hex) VALUES ('Lavender Pinocchio', '#EBDDE2');
INSERT INTO colors (name, hex) VALUES ('Lavender blue', '#E3E4FA');
INSERT INTO colors (name, hex) VALUES ('Pearl', '#FDEEF4');
INSERT INTO colors (name, hex) VALUES ('SeaShell', '#FFF5EE');
INSERT INTO colors (name, hex) VALUES ('Milk White', '#FEFCFF');
INSERT INTO colors (name, hex) VALUES ('White', '#FFFFFF');
